name: Build

on:
  push:
    branches:
      - master

env:
  GH_API_ROOT: https://api.github.com/repos/p5-net-ssleay/ci-strawberry-perl

jobs:
  build:
    name: 'Strawberry Perl ${{ matrix.version }} ${{ matrix.flavour }}'
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        version:
          - '5.24.1.1'
        flavour:
          - x64
        #exclude:
    steps:
      - name: Check out ci-strawberry-perl
        uses: actions/checkout@v2

      - name: Check out p5-net-ssleay
        uses: actions/checkout@v2
        with:
          repository: radiator-software/p5-net-ssleay
          ref: master
          path: p5-net-ssleay

      - name: Install Strawberry Perl ${{ matrix.version }} ${{ matrix.flavour }}
        run: |
          $filename = switch ("${{ matrix.flavour }}") {
            "x64"      { "strawberry-perl-${{ matrix.version }}-64bit.zip" }
            "x86"      { "strawberry-perl-${{ matrix.version }}-32bit.zip" }
            "x86_no64" { "strawberry-perl-no64-${{ matrix.version }}-32bit.zip" }
          }
          
          Invoke-WebRequest `
            -Uri https://strawberryperl.com/download/${{ matrix.version }}/$filename `
            -OutFile strawberry.zip

          Expand-Archive `
            -Path strawberry.zip `
            -DestinationPath C:\strawberry

          if (Test-Path -Path C:\strawberry\relocation.pl.bat -PathType Leaf) {
            C:\strawberry\relocation.pl.bat
          }

          if (Test-Path -Path C:\strawberry\c\bin\dmake.exe -PathType Leaf) {
            $make = "C:\strawberry\c\bin\dmake.exe"
          }
          else {
            $make = "C:\strawberry\c\bin\gmake.exe"
          }

          $env:Path = "C:\strawberry\perl\bin;C:\strawberry\c\bin;$env:Path"

      - name: Restore cached Process Monitor executable
        uses: actions/cache@v2
        with:
          path: Procmon64.exe
          key: procmon

      - name: Start Process Monitor
        run: |
          if (-not(Test-Path -Path Procmon64.exe -PathType Leaf)) {
            Invoke-WebRequest `
              -Uri https://download.sysinternals.com/files/ProcessMonitor.zip `
              -OutFile ProcessMonitor.zip

            Expand-Archive `
              -Path ProcessMonitor.zip
          }

          #Procmon64 /AcceptEula /LoadConfig strawberry.pmc /BackingFile test.pml /Quiet /Minimized
          #Procmon64 /AcceptEula /WaitForIdle

      - name: Debug shell
        uses: mxschmitt/action-tmate@v3
        with:
          timeout-minutes: 10
          limit-access-to-actor: true

      - name: Run Net-SSLeay test suite
        run: |
          cd p5-net-ssleay
          echo n | perl Makefile.PL

          Start-Process `
            -FilePath $make `
            -NoNewWindow `
            -Wait

          Start-Process `
            -FilePath $make `
            -ArgumentList "test" `
            -NoNewWindow `
            -Wait

          cd ..

      - name: Stop Process Monitor
        run: |
          Procmon64 /AcceptEula /Terminate

      - name: Extract list of accessed Strawberry Perl paths
        run: |
          Procmon64 /AcceptEula /OpenLog test.pml /SaveAs test.csv

          Import-Csv test.csv | Select Path -Unique | Sort Path

      - name: Debug shell
        uses: mxschmitt/action-tmate@v3
        with:
          timeout-minutes: 10
          limit-access-to-actor: true
